data: 
  path_to_test_file: "/data/bcifuentes/outp/2025_splits/OTMC/P8/*.root"  
  path_to_outdir: "/data/bcifuentes/outp/2025_scores_NC/data"
  weights_file: ""
  scale_factor: 1
  kT_cut: 0 ## indeed this is a cut in ln(kT)

test:
  path_to_combined_ckpt: "/data/bcifuentes/outp/2025_Models_NC/LundNet_R22_ln_kT_Cut_0.0_LRJ_NewDatae030_0.09521.pt"
  output_name: "LundNet_R22_ln_kT_Cut_0.0_LRJ_NewDatae030"
  choose_model: "LundNet"
  learning_rate: 0.001
  batch_size: 2000
