data:
  path_to_trainfiles: "/data/bcifuentes/outp/2025_splits_NV/TRAIN_1MIXQCD_5P8TOP/*.root"
  path_to_save: "/data/bcifuentes/outp/2025_graphs_dsids/"
  model_name: "LundNet_R22_1MIXQCD_5P8TOP"

architecture:
  batch_size: 1200
  test_size: 0.2
  n_epochs: 30
  learning_rate: 0.0005
  kT_cut: -500 ## indeed this is a cut in ln(kT)
  choose_model: LundNet ## LundNet, GATNet, GINNet, EdgeGinNet, PNANet
  save_every_epoch: True

retrain:
  flag: False
  path_to_ckpt: "/sps/atlas/k/khandoga/TrainGNN/Models/LundNet_ufob_e012_0.12481.pt"
