data: 
  path_to_test_file: "/data/bcifuentes/outp/top_train05_test_05/SherpaCluster*Top/*test.root"  
  path_to_outdir: "/data/bcifuentes/outp/2025_scores_1qcd_5s/cut_2_Primary"
  weights_file: ""
  scale_factor: 1
  kT_cut: 2 ## indeed this is a cut in ln(kT)

test:
  path_to_combined_ckpt: "/data/bcifuentes/outp/2025_MODELS/2025_Models_1qcd_5top_ktcut_2_Primary/LundNet_R22_ln_kT_Cut_2_LRJ_NewData_Primarye017_0.83189.pt"
  output_name: "TESTSHERPAC"
  choose_model: "LundNet"
  learning_rate: 0.001
  batch_size: 2000
