data:
  path_to_trainfiles: "/data/bcifuentes/MAY_outp/2025_DATA/2025_DATA_5TOP_1QCD/*/*train.root"
  #path_to_trainfiles: "/data/ravinascos/Lund_Plane_2025_graphs/Mix_SignalW10/*/*train.root"
  #path_to_trainfiles: "/data/ravinascos/Lund_Plane_2025_graphs/Mix_SignalW10/*/*train.root"
  #path_to_save: "/data/ravinascos/LundNet/2025_graphs/"
  path_to_save: "/data/bcifuentes/MAY_outp/2025_MODELS/2025_MODELS_BS2000_LR0002/"
  model_name: "LundNet_R22_1MIXQCD_5P8TOP_BS2000_LR0002_MANUAL"
  #model_name: "LundNet_R22_No_ln_kT_Cut_LRJ_NewNtrk_W_qcd01_W10_primary"
  #kT_cut: -500 ## indeed this is a cut in ln(kT)

architecture:
  batch_size: 2000
  test_size: 0.1
  n_epochs: 20
  learning_rate: 0.0002
  kT_cut: -500 ## indeed this is a cut in ln(kT)
  choose_model: LundNet ## LundNet, GATNet, GINNet, EdgeGinNet, PNANet
  save_every_epoch: True

retrain:
  flag: False
  path_to_ckpt: "/sps/atlas/k/khandoga/TrainGNN/Models/LundNet_ufob_e012_0.12481.pt"


data_test: 
  do_all_MC: 1  # 1->Do all MC ; 0-> Only Phythia
  path_to_test_file_pythia: "/data/bcifuentes/MAY_outp/2025_DATA/2025_DATA_TEST/Pythia*/*test.root"
  path_to_test_file_HerwigDipole: "/data/bcifuentes/MAY_outp/2025_DATA/2025_DATA_TEST/HerwigDipole*/*test.root"
  path_to_test_file_HerwigAngular: "/data/bcifuentes/MAY_outp/2025_DATA/2025_DATA_TEST/HerwigAngular*/*test.root"
  path_to_test_file_SherpaCluster: "/data/bcifuentes/MAY_outp/2025_DATA/2025_DATA_TEST/SherpaCluster*/*test.root"
  path_to_test_file_SherpaLund: "/data/bcifuentes/MAY_outp/2025_DATA/2025_DATA_TEST/SherpaLund*/*test.root"
  path_to_outdir: "/data/bcifuentes/MAY_outp/2025_SCORES/scores_1MIXQCD_5P8TOP_BS2000_LR0002_MANUAL/"
  weights_file: ""
  scale_factor: 1

test:
  path_to_combined_ckpt: "/data/bcifuentes/MAY_outp/2025_MODELS/2025_MODELS_BS4800_LR0002/LundNet_R22_15MIXQCD_75P8TOPe019_0.50989.pt"
  output_name: "LundNet_R22_1MIXQCD_5P8TOP_BS2000_LR0002"
  choose_model: "LundNet"
  learning_rate: 0.001
  batch_size: 2000
