data:
  path_to_trainfiles: "/data/bcifuentes/outp/2025_graphs_NC/graphs_NewDataset_LundNet_R22_ln_kT_Cut_2.8_LRJ_NewData"
  path_to_save: "/data/bcifuentes/outp/2025_Models_NC/"
  model_name: "LundNet_R22_ln_kT_Cut_2.8_LRJ_NewData"

architecture:
  batch_size: 4500
  test_size: 0.1
  n_epochs: 30
  learning_rate: 0.0005
  choose_model: LundNet ## LundNet, GATNet, GINNet, EdgeGinNet, PNANet
  save_every_epoch: True

retrain:
  flag: False
  path_to_ckpt: "/sps/atlas/k/khandoga/TrainGNN/Models/LundNet_ufob_e012_0.12481.pt"
